import { getStockList } from '../storage/stocklist.js';
import { getStage, analyzeSymbolsNow } from './stage.js';
import { expectedTradingDate } from '../data/calendar.js';
import { KEYS } from '../storage/kv-schema.js';
import { parseJson, nowIso, finite, round } from '../utils.js';

const SRC={jp:'https://finance.yahoo.co.jp/stocks/ranking/tradingValueHigh?market=all',us:'https://finance.yahoo.co.jp/stocks/us/ranking/tradingValue?market=all'};
const LIMIT={jp:300,us:100},PAGE=50,HISTORY_DAYS=45;
function normalize(code,market){if(!code)return null;let s=String(code).toUpperCase();if(market==='jp'){if(s.startsWith('^')||s.includes('='))return null;if(/\.T$/.test(s))return s;if(/^[0-9A-Z]{4}$/.test(s))return s+'.T';return null;}if(s.includes('.')||s.startsWith('^')||s.includes('='))return null;return/^[A-Z]{1,6}$/.test(s)?s:null;}
function fund(symbol,name){const n=String(name||'');if(/(ETF|ETN|上場投信|投資信託|ファンド|レバレッジ|インバース|ブル|ベア|NEXT FUNDS|MAXIS|iシェアーズ|グローバルX|REIT|リート)/i.test(n))return true;if(/\.T$/.test(symbol)){const x=parseInt(symbol,10);if((x>=1300&&x<=1599)||(x>=2500&&x<=2599))return true;}return false;}
function nameFrom(segment){const tag=segment.match(/>([^<>]{2,50}?)<\/a>/);if(tag)return tag[1].trim();const md=segment.match(/\[([^\]]{2,50}?)\]\(/);return md?md[1].trim():null;}
function valueFrom(segment,market){const min=market==='jp'?1e7:1000,nums=[];for(const m of segment.matchAll(/([0-9]{1,3}(?:,[0-9]{3})+)(千)?/g)){let v=parseInt(m[1].replace(/,/g,''),10);if(m[2])v*=1000;if(v>=min)nums.push(v);}return nums.length?Math.max(...nums):null;}
function parseRanking(html,market,offset=0){const re=/\/quote\/([A-Za-z0-9.\-]+?)(?:["'\/?])/g,pos=[];let m;while((m=re.exec(html))){if(html.slice(m.index,m.index+50).includes('/forum'))continue;const s=normalize(m[1],market);if(s&&!pos.some(x=>x.symbol===s))pos.push({symbol:s,index:m.index});}
  const out=[];for(let i=0;i<pos.length;i++){const seg=html.slice(pos[i].index,pos[i+1]?.index||Math.min(html.length,pos[i].index+4000)),name=nameFrom(seg)||pos[i].symbol;if(fund(pos[i].symbol,name)||/(レポート|アナリスト|広告|sponsored|フィスコ)/i.test(name))continue;out.push({rank:offset+out.length+1,symbol:pos[i].symbol,name,value:valueFrom(seg,market)});}return out;}
async function fetchPage(market,page){const url=SRC[market]+(SRC[market].includes('?')?'&':'?')+'page='+page,res=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 (compatible; VANTAGE/35.0)','Accept':'text/html'},cf:{cacheTtl:300}});if(!res.ok)throw new Error(`ranking HTTP ${res.status}`);return res.text();}
async function history(env,market){return parseJson(await env.COCKPIT_KV.get(KEYS.rankingHistory(market)),{snapshots:[]});}
async function saveHistory(env,market,payload){const h=await history(env,market),date=payload.trade_date;h.snapshots=(h.snapshots||[]).filter(x=>x.date!==date);h.snapshots.push({date,updated_at:payload.updated_at,items:payload.items.map(x=>({symbol:x.symbol,rank:x.rank,value:x.value}))});h.snapshots.sort((a,b)=>String(a.date).localeCompare(String(b.date)));h.snapshots=h.snapshots.slice(-HISTORY_DAYS);await env.COCKPIT_KV.put(KEYS.rankingHistory(market),JSON.stringify(h));return h;}
export async function refreshRanking(env,market){const max=LIMIT[market],all=[],seen=new Set();for(let p=1;p<=Math.ceil(max/PAGE);p++){const items=parseRanking(await fetchPage(market,p),market,all.length);for(const x of items){if(!seen.has(x.symbol)){seen.add(x.symbol);all.push({...x,rank:all.length+1});if(all.length>=max)break;}}if(all.length>=max||items.length<PAGE)break;}
  const payload={ok:true,market,source:'Yahoo!ファイナンス 売買代金ランキング',updated_at:nowIso(),trade_date:expectedTradingDate(market),count:all.length,items:all};await env.COCKPIT_KV.put(KEYS.ranking(market),JSON.stringify(payload));await saveHistory(env,market,payload);return payload;}
export async function getRanking(env,market,force=false){let x=force?null:parseJson(await env.COCKPIT_KV.get(KEYS.ranking(market)),null);if(!x)x=await refreshRanking(env,market);return x;}
function movement(items,prev){const pm=new Map((prev?.items||[]).map(x=>[x.symbol,x.rank]));return items.map(x=>({...x,new_entry:!pm.has(x.symbol),rank_change:pm.has(x.symbol)?pm.get(x.symbol)-x.rank:null}));}
function mergeAnalysis(item,a,registered){return{...item,registered,price:a?.price??null,change_pct:a?.change_pct??null,price_time:a?.price_time??null,date:a?.date??null,close_confirmed:a?.data_quality?.close_confirmed??null,stage:a?.long_stage??null,stage_code:a?.stage_code??null,vol_ratio:a?.vol_ratio??null,div25:a?.div25??null,ret5:a?.ret5??null,ret20:a?.ret20??null,rs5:a?.rs5??null,rsi:a?.rsi14??null,entry_lane:a?.entry_lane??null,theme:a?.theme??null};}
export async function getEnrichedRanking(env,market,force=false){const ranking=await getRanking(env,market,force),h=await history(env,market),prev=(h.snapshots||[]).filter(x=>x.date!==ranking.trade_date).at(-1),moved=movement(ranking.items||[],prev),registered=await getStockList(env,market),reg=new Set(registered.map(x=>x.symbol)),stage=await getStage(env,market),top=moved.slice(0,50),unknown=top.filter(x=>!reg.has(x.symbol)&&!stage.stocks?.[x.symbol]).slice(0,35);
  const analyzed=unknown.length?await analyzeSymbolsNow(env,unknown,market,{label:'RANK',cacheTtl:60}):{items:[]},amap=new Map((analyzed.items||[]).filter(Boolean).map(x=>[x.symbol,x]));
  const items=top.map(x=>mergeAnalysis(x,stage.stocks?.[x.symbol]||amap.get(x.symbol)||null,reg.has(x.symbol)));
  return{ok:true,market,updated_at:nowIso(),ranking_updated_at:ranking.updated_at,ranking_trade_date:ranking.trade_date,ranking_count:ranking.count,history_days:(h.snapshots||[]).length,previous_trade_date:prev?.date||null,items};}
function score(item,a){let s=0,reasons=[],cautions=[];if(item.rank<=30){s+=25;reasons.push('売買代金上位');}else if(item.rank<=80){s+=15;reasons.push('流動性上位');}if(item.new_entry){s+=15;reasons.push('新規ランクイン');}if((item.rank_change||0)>=20){s+=15;reasons.push(`順位+${item.rank_change}`);}if(finite(a?.vol_ratio)&&a.vol_ratio>=1.2){s+=15;reasons.push(`出来高${a.vol_ratio}倍`);}if(finite(a?.rs5)&&a.rs5>=2){s+=15;reasons.push(`市場RS ${a.rs5}%`);}if(['S2'].includes(a?.stage_code)){s+=10;reasons.push('上昇レジーム');}if(finite(a?.div25)&&Math.abs(a.div25)<=5){s+=8;reasons.push('25MA近辺');}if(finite(a?.rsi14)&&a.rsi14>=78){s-=20;cautions.push('RSI過熱');}if(finite(a?.div25)&&a.div25>=12){s-=20;cautions.push('25MAから過熱');}return{score:Math.max(0,Math.min(100,s)),reasons,cautions,recommendation:s>=55?'add':s>=35?'watch':'skip'};}
export async function buildExplorer(env,market='jp',force=false){if(market!=='jp')return{ok:false,error:'探索は日本株専用です'};const ranking=await getRanking(env,'jp',force),h=await history(env,'jp'),prev=(h.snapshots||[]).filter(x=>x.date!==ranking.trade_date).at(-1),moved=movement(ranking.items||[],prev),registered=await getStockList(env,'jp'),reg=new Set(registered.map(x=>x.symbol)),pool=moved.filter(x=>!reg.has(x.symbol)).slice(0,80),selected=pool.sort((a,b)=>((b.new_entry?20:0)+(b.rank_change||0))-((a.new_entry?20:0)+(a.rank_change||0))).slice(0,35);
  const batch=await analyzeSymbolsNow(env,selected,'jp',{label:'EXPLORER',cacheTtl:60}),amap=new Map((batch.items||[]).filter(Boolean).map(x=>[x.symbol,x]));
  const analyzed=selected.map(x=>{const a=amap.get(x.symbol)||null,ev=score(x,a);return{...x,...a,...ev,type:ev.recommendation==='add'?'資金流入候補':'観察候補'};});
  const items=analyzed.filter(x=>x.recommendation!=='skip').sort((a,b)=>b.score-a.score).slice(0,24),skipped=analyzed.filter(x=>x.recommendation==='skip').sort((a,b)=>b.score-a.score).slice(0,12),payload={ok:true,market:'jp',generated_at:nowIso(),ranking_updated_at:ranking.updated_at,ranking_trade_date:ranking.trade_date,ranking_count:ranking.count,history_days:(h.snapshots||[]).length,registered_count:registered.length,core_count:Math.min(80,registered.length),radar_count:Math.max(0,registered.length-80),remaining_slots:Math.max(0,160-registered.length),analyzed_count:analyzed.length,add_count:items.filter(x=>x.recommendation==='add').length,watch_count:items.filter(x=>x.recommendation==='watch').length,items,skipped};await env.COCKPIT_KV.put(KEYS.explorer('jp'),JSON.stringify(payload));return payload;}
export async function getExplorer(env,market='jp',force=false){if(force)return buildExplorer(env,market,true);const old=parseJson(await env.COCKPIT_KV.get(KEYS.explorer(market)),null);return old||buildExplorer(env,market,false);}
